In [1]:
import numpy as np
import pandas as pd

In [2]:
users_list = pd.read_table('data/ml-1m/users.dat',
                      sep='::', header=None, 
                      names=['user_id', 'gender', 'age', 'occupation', 'zip'], engine='python')

ratings_list = pd.read_table('data/ml-1m/ratings.dat',
                        sep='::', header=None, 
                        names=['user_id', 'movie_id', 'rating', 'timestamp'], engine='python')

movies_list = pd.read_table('data/ml-1m/movies.dat',
                       sep='::', header=None, 
                       names=['movie_id', 'title', 'genres'], engine='python')

In [3]:
movies_list.head()

   movie_id                               title                        genres
0         1                    Toy Story (1995)   Animation|Children's|Comedy
1         2                      Jumanji (1995)  Adventure|Children's|Fantasy
2         3             Grumpier Old Men (1995)                Comedy|Romance
3         4            Waiting to Exhale (1995)                  Comedy|Drama
4         5  Father of the Bride Part II (1995)                        Comedy

In [4]:
ratings_list.head()

   user_id  movie_id  rating  timestamp
0        1      1193       5  978300760
1        1       661       3  978302109
2        1       914       3  978301968
3        1      3408       4  978300275
4        1      2355       5  978824291

In [65]:
movies_list = pd.concat([movies_list, movies_list.genres.str.get_dummies(sep='|')], axis=1)  
movies_list.head(5)

,movie_id,title,genres,Action,Adventure,Animation,Children's,Comedy,Crime,Documentary,...,Fantasy,Film-Noir,Horror,Musical,Mystery,Romance,Sci-Fi,Thriller,War,Western
0,1,Toy Story (1995),Animation|Children's|Comedy,0,0,2,1,1,0,0,...,0,0,0,0,0,0,0,0,0,0
1,2,Jumanji (1995),Adventure|Children's|Fantasy,0,2,0,1,0,0,0,...,1,0,0,0,0,0,0,0,0,0
2,3,Grumpier Old Men (1995),Comedy|Romance,0,0,0,0,2,0,0,...,0,0,0,0,0,1,0,0,0,0
3,4,Waiting to Exhale (1995),Comedy|Drama,0,0,0,0,2,0,0,...,0,0,0,0,0,0,0,0,0,0
4,5,Father of the Bride Part II (1995),Comedy,0,0,0,0,2,0,0,...,0,0,0,0,0,0,0,0,0,0

In [6]:
for index, row in movies_list.iterrows():
    main_g = row['genres'].split("|")[0]
    movies_list.loc[index , main_g] = 2

In [66]:
movies_list.head(5)

,movie_id,title,genres,Action,Adventure,Animation,Children's,Comedy,Crime,Documentary,...,Fantasy,Film-Noir,Horror,Musical,Mystery,Romance,Sci-Fi,Thriller,War,Western
0,1,Toy Story (1995),Animation|Children's|Comedy,0,0,2,1,1,0,0,...,0,0,0,0,0,0,0,0,0,0
1,2,Jumanji (1995),Adventure|Children's|Fantasy,0,2,0,1,0,0,0,...,1,0,0,0,0,0,0,0,0,0
2,3,Grumpier Old Men (1995),Comedy|Romance,0,0,0,0,2,0,0,...,0,0,0,0,0,1,0,0,0,0
3,4,Waiting to Exhale (1995),Comedy|Drama,0,0,0,0,2,0,0,...,0,0,0,0,0,0,0,0,0,0
4,5,Father of the Bride Part II (1995),Comedy,0,0,0,0,2,0,0,...,0,0,0,0,0,0,0,0,0,0

In [8]:
geners = list(movies_list)[3:]
geners

['Action',
 'Adventure',
 'Animation',
 "Children's",
 'Comedy',
 'Crime',
 'Documentary',
 'Drama',
 'Fantasy',
 'Film-Noir',
 'Horror',
 'Musical',
 'Mystery',
 'Romance',
 'Sci-Fi',
 'Thriller',
 'War',
 'Western']

In [9]:
movies_ratings = pd.merge(ratings_list,movies_list,on='movie_id', how='left')
movies_ratings.head()

,user_id,movie_id,rating,timestamp,title,genres,Action,Adventure,Animation,Children's,...,Fantasy,Film-Noir,Horror,Musical,Mystery,Romance,Sci-Fi,Thriller,War,Western
0,1,1193,5,978300760,One Flew Over the Cuckoo's Nest (1975),Drama,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
1,1,661,3,978302109,James and the Giant Peach (1996),Animation|Children's|Musical,0,0,2,1,...,0,0,0,1,0,0,0,0,0,0
2,1,914,3,978301968,My Fair Lady (1964),Musical|Romance,0,0,0,0,...,0,0,0,2,0,1,0,0,0,0
3,1,3408,4,978300275,Erin Brockovich (2000),Drama,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
4,1,2355,5,978824291,"Bug's Life, A (1998)",Animation|Children's|Comedy,0,0,2,1,...,0,0,0,0,0,0,0,0,0,0

In [10]:
movieslens = pd.merge(movies_ratings,users_list,on='user_id',how='left')

In [11]:
movieslens.head()

,user_id,movie_id,rating,timestamp,title,genres,Action,Adventure,Animation,Children's,...,Mystery,Romance,Sci-Fi,Thriller,War,Western,gender,age,occupation,zip
0,1,1193,5,978300760,One Flew Over the Cuckoo's Nest (1975),Drama,0,0,0,0,...,0,0,0,0,0,0,F,1,10,48067
1,1,661,3,978302109,James and the Giant Peach (1996),Animation|Children's|Musical,0,0,2,1,...,0,0,0,0,0,0,F,1,10,48067
2,1,914,3,978301968,My Fair Lady (1964),Musical|Romance,0,0,0,0,...,0,1,0,0,0,0,F,1,10,48067
3,1,3408,4,978300275,Erin Brockovich (2000),Drama,0,0,0,0,...,0,0,0,0,0,0,F,1,10,48067
4,1,2355,5,978824291,"Bug's Life, A (1998)",Animation|Children's|Comedy,0,0,2,1,...,0,0,0,0,0,0,F,1,10,48067

In [12]:
movieslens.shape

(1000209, 28)

In [13]:
movieslens_sl2 = movieslens[:50000]
movieslens_sl2

,user_id,movie_id,rating,timestamp,title,genres,Action,Adventure,Animation,Children's,...,Mystery,Romance,Sci-Fi,Thriller,War,Western,gender,age,occupation,zip
0,1,1193,5,978300760,One Flew Over the Cuckoo's Nest (1975),Drama,0,0,0,0,...,0,0,0,0,0,0,F,1,10,48067
1,1,661,3,978302109,James and the Giant Peach (1996),Animation|Children's|Musical,0,0,2,1,...,0,0,0,0,0,0,F,1,10,48067
2,1,914,3,978301968,My Fair Lady (1964),Musical|Romance,0,0,0,0,...,0,1,0,0,0,0,F,1,10,48067
3,1,3408,4,978300275,Erin Brockovich (2000),Drama,0,0,0,0,...,0,0,0,0,0,0,F,1,10,48067
4,1,2355,5,978824291,"Bug's Life, A (1998)",Animation|Children's|Comedy,0,0,2,1,...,0,0,0,0,0,0,F,1,10,48067
5,1,1197,3,978302268,"Princess Bride, The (1987)",Action|Adventure|Comedy|Romance,2,1,0,0,...,0,1,0,0,0,0,F,1,10,48067
6,1,1287,5,978302039,Ben-Hur (1959),Action|Adventure|Drama,2,1,0,0,...,0,0,0,0,0,0,F,1,10,48067
7,1,2804,5,978300719,"Christmas Story, A (1983)",Comedy|Drama,0,0,0,0,...,0,0,0,0,0,0,F,1,10,48067
8,1,594,4,978302268,Snow White and the Seven Dwarfs (1937),Animation|Children's|Musical,0,0,2,1,...,0,0,0,0,0,0,F,1,10,48067
9,1,919,4,978301368,"Wizard of Oz, The (1939)",Adventure|Children's|Drama|Musical,0,2,0,1,...,0,0,0,0,0,0,F,1,10,48067
10,1,595,5,978824268,Beauty and the Beast (1991),Animation|Children's|Musical,0,0,2,1,...,0,0,0,0,0,0,F,1,10,48067
11,1,938,4,978301752,Gigi (1958),Musical,0,0,0,0,...,0,0,0,0,0,0,F,1,10,48067
12,1,2398,4,978302281,Miracle on 34th Street (1947),Drama,0,0,0,0,...,0,0,0,0,0,0,F,1,10,48067
13,1,2918,4,978302124,Ferris Bueller's Day Off (1986),Comedy,0,0,0,0,...,0,0,0,0,0,0,F,1,10,48067
14,1,1035,5,978301753,"Sound of Music, The (1965)",Musical,0,0,0,0,...,0,0,0,0,0,0,F,1,10,48067
15,1,2791,4,978302188,Airplane! (1980),Comedy,0,0,0,0,...,0,0,0,0,0,0,F,1,10,48067
16,1,2687,3,978824268,Tarzan (1999),Animation|Children's,0,0,2,1,...,0,0,0,0,0,0,F,1,10,48067
17,1,2018,4,978301777,Bambi (1942),Animation|Children's,0,0,2,1,...,0,0,0,0,0,0,F,1,10,48067
18,1,3105,5,978301713,Awakenings (1990),Drama,0,0,0,0,...,0,0,0,0,0,0,F,1,10,48067
19,1,2797,4,978302039,Big (1988),Comedy|Fantasy,0,0,0,0,...,0,0,0,0,0,0,F,1,10,48067
20,1,2321,3,978302205,Pleasantville (1998),Comedy,0,0,0,0,...,0,0,0,0,0,0,F,1,10,48067
21,1,720,3,978300760,Wallace & Gromit: The Best of Aardman Animatio...,Animation,0,0,2,0,...,0,0,0,0,0,0,F,1,10,48067
22,1,1270,5,978300055,Back to the Future (1985),Comedy|Sci-Fi,0,0,0,0,...,0,0,1,0,0,0,F,1,10,48067
23,1,527,5,978824195,Schindler's List (1993),Drama|War,0,0,0,0,...,0,0,0,0,1,0,F,1,10,48067
24,1,2340,3,978300103,Meet Joe Black (1998),Romance,0,0,0,0,...,0,2,0,0,0,0,F,1,10,48067
25,1,48,5,978824351,Pocahontas (1995),Animation|Children's|Musical|Romance,0,0,2,1,...,0,1,0,0,0,0,F,1,10,48067
26,1,1097,4,978301953,E.T. the Extra-Terrestrial (1982),Children's|Drama|Fantasy|Sci-Fi,0,0,0,2,...,0,0,1,0,0,0,F,1,10,48067
27,1,1721,4,978300055,Titanic (1997),Drama|Romance,0,0,0,0,...,0,1,0,0,0,0,F,1,10,48067
28,1,1545,4,978824139,Ponette (1996),Drama,0,0,0,0,...,0,0,0,0,0,0,F,1,10,48067
29,1,745,3,978824268,"Close Shave, A (1995)",Animation|Comedy|Thriller,0,0,2,0,...,0,0,0,1,0,0,F,1,10,48067
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
49970,331,2331,4,976385799,Living Out Loud (1998),Comedy|Romance,0,0,0,0,...,0,1,0,0,0,0,M,25,7,55902
49971,331,2406,3,1000395737,Romancing the Stone (1984),Action|Adventure|Comedy|Romance,2,1,0,0,...,0,1,0,0,0,0,M,25,7,55902
49972,331,2334,2,979855365,"Siege, The (1998)",Action|Thriller,2,0,0,0,...,0,0,0,1,0,0,M,25,7,55902
49973,331,1608,3,979855458,Air Force One (1997),Action|Thriller,2,0,0,0,...,0,0,0,1,0,0,M,25,7,55902
49974,331,1535,4,978884061,Love! Valour! Compassion! (1997),Drama|Romance,0,0,0,0,...,0,1,0,0,0,0,M,25,7,55902
49975,331,3068,5,976849806,"Verdict, The (1982)",Drama,0,0,0,0,...,0,0,0,0,0,0,M,25,7,55902
49976,331,1537,5,976386123,Shall We Dance? (Shall We Dansu?) (1996),Comedy,0,0,0,0,...,0,0,0,0,0,0,M,25,7,55902
49977,331,2267,4,1000153251,Mortal Thoughts (1991),Mystery|Thriller,0,0,0,0,...,2,0,0,1,0,0,M,25,7,55902
49978,331,2194,3,1000330959,"Untouchables, The (1987)",Action|Crime|Drama,2,0,0,0,...,0,0,0,0,0,0,M,25,7,55902
49979,331,2268,3,978884187,"Few Good Men, A (1992)",Crime|Drama,0,0,0,0,...,0,0,0,0,0,0,M,25,7,55902
49980,331,1466,4,978884007,Donnie Brasco (1997),Crime|Drama,0,0,0,0,...,0,0,0,0,0,0,M,25,7,55902
49981,331,1393,5,976385545,Jerry Maguire (1996),Drama|Romance,0,0,0,0,...,0,1,0,0,0,0,M,25,7,55902
49982,331,2269,4,978884785,Indecent Proposal (1993),Drama,0,0,0,0,...,0,0,0,0,0,0,M,25,7,55902
49983,331,1394,3,1000396229,Raising Arizona (1987),Comedy,0,0,0,0,...,0,0,0,0,0,0,M,25,7,55902
49984,331,1396,3,1000323755,Sneakers (1992),Crime|Drama|Sci-Fi,0,0,0,0,...,0,0,1,0,0,0,M,25,7,55902
49985,331,866,5,976385571,Bound (1996),Crime|Drama|Romance|Thriller,0,0,0,0,...,0,1,0,1,0,0,M,25,7,55902
49986,331,3210,4,1000396229,Fast Times at Ridgemont High (1982),Comedy,0,0,0,0,...,0,0,0,0,0,0,M,25,7,55902
49987,331,2412,1,984152710,Rocky V (1990),Action|Drama,2,0,0,0,...,0,0,0,0,0,0,M,25,7,55902
49988,331,1610,4,984152293,"Hunt for Red October, The (1990)",Action|Thriller,2,0,0,0,...,0,0,0,1,0,0,M,25,7,55902
49989,331,2340,4,976385824,Meet Joe Black (1998),Romance,0,0,0,0,...,0,2,0,0,0,0,M,25,7,55902
49990,331,3071,5,1000331075,Stand and Deliver (1987),Drama,0,0,0,0,...,0,0,0,0,0,0,M,25,7,55902
49991,331,3072,5,1000396229,Moonstruck (1987),Comedy,0,0,0,0,...,0,0,0,0,0,0,M,25,7,55902
49992,331,1614,4,976849098,In & Out (1997),Comedy,0,0,0,0,...,0,0,0,0,0,0,M,25,7,55902
49993,331,2271,3,978884729,Permanent Midnight (1998),Drama,0,0,0,0,...,0,0,0,0,0,0,M,25,7,55902
49994,331,1615,3,979855365,"Edge, The (1997)",Adventure|Thriller,0,2,0,0,...,0,0,0,1,0,0,M,25,7,55902
49995,331,1542,4,976385747,Brassed Off (1996),Comedy|Drama|Romance,0,0,0,0,...,0,1,0,0,0,0,M,25,7,55902
49996,331,3147,4,978884127,"Green Mile, The (1999)",Drama|Thriller,0,0,0,0,...,0,0,0,1,0,0,M,25,7,55902
49997,331,2272,5,978884278,One True Thing (1998),Drama,0,0,0,0,...,0,0,0,0,0,0,M,25,7,55902
49998,331,1616,3,979855459,"Peacemaker, The (1997)",Action|Thriller|War,2,0,0,0,...,0,0,0,1,1,0,M,25,7,55902
49999,331,2273,4,979855365,Rush Hour (1998),Action|Thriller,2,0,0,0,...,0,0,0,1,0,0,M,25,7,55902

In [14]:
movieslens_sl2.shape

(50000, 28)

In [15]:
movieslens_sl2[geners].head()

,Action,Adventure,Animation,Children's,Comedy,Crime,Documentary,Drama,Fantasy,Film-Noir,Horror,Musical,Mystery,Romance,Sci-Fi,Thriller,War,Western
0,0,0,0,0,0,0,0,2,0,0,0,0,0,0,0,0,0,0
1,0,0,2,1,0,0,0,0,0,0,0,1,0,0,0,0,0,0
2,0,0,0,0,0,0,0,0,0,0,0,2,0,1,0,0,0,0
3,0,0,0,0,0,0,0,2,0,0,0,0,0,0,0,0,0,0
4,0,0,2,1,1,0,0,0,0,0,0,0,0,0,0,0,0,0

In [16]:
movieslens_sl2

,user_id,movie_id,rating,timestamp,title,genres,Action,Adventure,Animation,Children's,...,Mystery,Romance,Sci-Fi,Thriller,War,Western,gender,age,occupation,zip
0,1,1193,5,978300760,One Flew Over the Cuckoo's Nest (1975),Drama,0,0,0,0,...,0,0,0,0,0,0,F,1,10,48067
1,1,661,3,978302109,James and the Giant Peach (1996),Animation|Children's|Musical,0,0,2,1,...,0,0,0,0,0,0,F,1,10,48067
2,1,914,3,978301968,My Fair Lady (1964),Musical|Romance,0,0,0,0,...,0,1,0,0,0,0,F,1,10,48067
3,1,3408,4,978300275,Erin Brockovich (2000),Drama,0,0,0,0,...,0,0,0,0,0,0,F,1,10,48067
4,1,2355,5,978824291,"Bug's Life, A (1998)",Animation|Children's|Comedy,0,0,2,1,...,0,0,0,0,0,0,F,1,10,48067
5,1,1197,3,978302268,"Princess Bride, The (1987)",Action|Adventure|Comedy|Romance,2,1,0,0,...,0,1,0,0,0,0,F,1,10,48067
6,1,1287,5,978302039,Ben-Hur (1959),Action|Adventure|Drama,2,1,0,0,...,0,0,0,0,0,0,F,1,10,48067
7,1,2804,5,978300719,"Christmas Story, A (1983)",Comedy|Drama,0,0,0,0,...,0,0,0,0,0,0,F,1,10,48067
8,1,594,4,978302268,Snow White and the Seven Dwarfs (1937),Animation|Children's|Musical,0,0,2,1,...,0,0,0,0,0,0,F,1,10,48067
9,1,919,4,978301368,"Wizard of Oz, The (1939)",Adventure|Children's|Drama|Musical,0,2,0,1,...,0,0,0,0,0,0,F,1,10,48067
10,1,595,5,978824268,Beauty and the Beast (1991),Animation|Children's|Musical,0,0,2,1,...,0,0,0,0,0,0,F,1,10,48067
11,1,938,4,978301752,Gigi (1958),Musical,0,0,0,0,...,0,0,0,0,0,0,F,1,10,48067
12,1,2398,4,978302281,Miracle on 34th Street (1947),Drama,0,0,0,0,...,0,0,0,0,0,0,F,1,10,48067
13,1,2918,4,978302124,Ferris Bueller's Day Off (1986),Comedy,0,0,0,0,...,0,0,0,0,0,0,F,1,10,48067
14,1,1035,5,978301753,"Sound of Music, The (1965)",Musical,0,0,0,0,...,0,0,0,0,0,0,F,1,10,48067
15,1,2791,4,978302188,Airplane! (1980),Comedy,0,0,0,0,...,0,0,0,0,0,0,F,1,10,48067
16,1,2687,3,978824268,Tarzan (1999),Animation|Children's,0,0,2,1,...,0,0,0,0,0,0,F,1,10,48067
17,1,2018,4,978301777,Bambi (1942),Animation|Children's,0,0,2,1,...,0,0,0,0,0,0,F,1,10,48067
18,1,3105,5,978301713,Awakenings (1990),Drama,0,0,0,0,...,0,0,0,0,0,0,F,1,10,48067
19,1,2797,4,978302039,Big (1988),Comedy|Fantasy,0,0,0,0,...,0,0,0,0,0,0,F,1,10,48067
20,1,2321,3,978302205,Pleasantville (1998),Comedy,0,0,0,0,...,0,0,0,0,0,0,F,1,10,48067
21,1,720,3,978300760,Wallace & Gromit: The Best of Aardman Animatio...,Animation,0,0,2,0,...,0,0,0,0,0,0,F,1,10,48067
22,1,1270,5,978300055,Back to the Future (1985),Comedy|Sci-Fi,0,0,0,0,...,0,0,1,0,0,0,F,1,10,48067
23,1,527,5,978824195,Schindler's List (1993),Drama|War,0,0,0,0,...,0,0,0,0,1,0,F,1,10,48067
24,1,2340,3,978300103,Meet Joe Black (1998),Romance,0,0,0,0,...,0,2,0,0,0,0,F,1,10,48067
25,1,48,5,978824351,Pocahontas (1995),Animation|Children's|Musical|Romance,0,0,2,1,...,0,1,0,0,0,0,F,1,10,48067
26,1,1097,4,978301953,E.T. the Extra-Terrestrial (1982),Children's|Drama|Fantasy|Sci-Fi,0,0,0,2,...,0,0,1,0,0,0,F,1,10,48067
27,1,1721,4,978300055,Titanic (1997),Drama|Romance,0,0,0,0,...,0,1,0,0,0,0,F,1,10,48067
28,1,1545,4,978824139,Ponette (1996),Drama,0,0,0,0,...,0,0,0,0,0,0,F,1,10,48067
29,1,745,3,978824268,"Close Shave, A (1995)",Animation|Comedy|Thriller,0,0,2,0,...,0,0,0,1,0,0,F,1,10,48067
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
49970,331,2331,4,976385799,Living Out Loud (1998),Comedy|Romance,0,0,0,0,...,0,1,0,0,0,0,M,25,7,55902
49971,331,2406,3,1000395737,Romancing the Stone (1984),Action|Adventure|Comedy|Romance,2,1,0,0,...,0,1,0,0,0,0,M,25,7,55902
49972,331,2334,2,979855365,"Siege, The (1998)",Action|Thriller,2,0,0,0,...,0,0,0,1,0,0,M,25,7,55902
49973,331,1608,3,979855458,Air Force One (1997),Action|Thriller,2,0,0,0,...,0,0,0,1,0,0,M,25,7,55902
49974,331,1535,4,978884061,Love! Valour! Compassion! (1997),Drama|Romance,0,0,0,0,...,0,1,0,0,0,0,M,25,7,55902
49975,331,3068,5,976849806,"Verdict, The (1982)",Drama,0,0,0,0,...,0,0,0,0,0,0,M,25,7,55902
49976,331,1537,5,976386123,Shall We Dance? (Shall We Dansu?) (1996),Comedy,0,0,0,0,...,0,0,0,0,0,0,M,25,7,55902
49977,331,2267,4,1000153251,Mortal Thoughts (1991),Mystery|Thriller,0,0,0,0,...,2,0,0,1,0,0,M,25,7,55902
49978,331,2194,3,1000330959,"Untouchables, The (1987)",Action|Crime|Drama,2,0,0,0,...,0,0,0,0,0,0,M,25,7,55902
49979,331,2268,3,978884187,"Few Good Men, A (1992)",Crime|Drama,0,0,0,0,...,0,0,0,0,0,0,M,25,7,55902
49980,331,1466,4,978884007,Donnie Brasco (1997),Crime|Drama,0,0,0,0,...,0,0,0,0,0,0,M,25,7,55902
49981,331,1393,5,976385545,Jerry Maguire (1996),Drama|Romance,0,0,0,0,...,0,1,0,0,0,0,M,25,7,55902
49982,331,2269,4,978884785,Indecent Proposal (1993),Drama,0,0,0,0,...,0,0,0,0,0,0,M,25,7,55902
49983,331,1394,3,1000396229,Raising Arizona (1987),Comedy,0,0,0,0,...,0,0,0,0,0,0,M,25,7,55902
49984,331,1396,3,1000323755,Sneakers (1992),Crime|Drama|Sci-Fi,0,0,0,0,...,0,0,1,0,0,0,M,25,7,55902
49985,331,866,5,976385571,Bound (1996),Crime|Drama|Romance|Thriller,0,0,0,0,...,0,1,0,1,0,0,M,25,7,55902
49986,331,3210,4,1000396229,Fast Times at Ridgemont High (1982),Comedy,0,0,0,0,...,0,0,0,0,0,0,M,25,7,55902
49987,331,2412,1,984152710,Rocky V (1990),Action|Drama,2,0,0,0,...,0,0,0,0,0,0,M,25,7,55902
49988,331,1610,4,984152293,"Hunt for Red October, The (1990)",Action|Thriller,2,0,0,0,...,0,0,0,1,0,0,M,25,7,55902
49989,331,2340,4,976385824,Meet Joe Black (1998),Romance,0,0,0,0,...,0,2,0,0,0,0,M,25,7,55902
49990,331,3071,5,1000331075,Stand and Deliver (1987),Drama,0,0,0,0,...,0,0,0,0,0,0,M,25,7,55902
49991,331,3072,5,1000396229,Moonstruck (1987),Comedy,0,0,0,0,...,0,0,0,0,0,0,M,25,7,55902
49992,331,1614,4,976849098,In & Out (1997),Comedy,0,0,0,0,...,0,0,0,0,0,0,M,25,7,55902
49993,331,2271,3,978884729,Permanent Midnight (1998),Drama,0,0,0,0,...,0,0,0,0,0,0,M,25,7,55902
49994,331,1615,3,979855365,"Edge, The (1997)",Adventure|Thriller,0,2,0,0,...,0,0,0,1,0,0,M,25,7,55902
49995,331,1542,4,976385747,Brassed Off (1996),Comedy|Drama|Romance,0,0,0,0,...,0,1,0,0,0,0,M,25,7,55902
49996,331,3147,4,978884127,"Green Mile, The (1999)",Drama|Thriller,0,0,0,0,...,0,0,0,1,0,0,M,25,7,55902
49997,331,2272,5,978884278,One True Thing (1998),Drama,0,0,0,0,...,0,0,0,0,0,0,M,25,7,55902
49998,331,1616,3,979855459,"Peacemaker, The (1997)",Action|Thriller|War,2,0,0,0,...,0,0,0,1,1,0,M,25,7,55902
49999,331,2273,4,979855365,Rush Hour (1998),Action|Thriller,2,0,0,0,...,0,0,0,1,0,0,M,25,7,55902

In [18]:
movieslens_sl22 = movieslens_sl2.apply(lambda row: -1*(row[geners]/row['rating']) if row['rating'] < 3 
     else row[geners]*row['rating'], axis=1)

In [19]:
mm_lence = movieslens_sl2[movieslens_sl2.columns[0:7]]

In [20]:
mm_lence[mm_lence['user_id'] == 4]

,user_id,movie_id,rating,timestamp,title,genres,Action
233,4,3468,5,978294008,"Hustler, The (1961)",Drama,0
234,4,1210,3,978293924,Star Wars: Episode VI - Return of the Jedi (1983),Action|Adventure|Romance|Sci-Fi|War,2
235,4,2951,4,978294282,"Fistful of Dollars, A (1964)",Action|Western,2
236,4,1214,4,978294260,Alien (1979),Action|Horror|Sci-Fi|Thriller,2
237,4,1036,4,978294282,Die Hard (1988),Action|Thriller,2
238,4,260,5,978294199,Star Wars: Episode IV - A New Hope (1977),Action|Adventure|Fantasy|Sci-Fi,2
239,4,2028,5,978294230,Saving Private Ryan (1998),Action|Drama|War,2
240,4,480,4,978294008,Jurassic Park (1993),Action|Adventure|Sci-Fi,2
241,4,1196,2,978294199,Star Wars: Episode V - The Empire Strikes Back...,Action|Adventure|Drama|Sci-Fi|War,2
242,4,1198,5,978294199,Raiders of the Lost Ark (1981),Action|Adventure,2
243,4,1954,5,978294282,Rocky (1976),Action|Drama,2
244,4,1097,4,978293964,E.T. the Extra-Terrestrial (1982),Children's|Drama|Fantasy|Sci-Fi,0
245,4,3418,4,978294260,Thelma & Louise (1991),Action|Drama,2
246,4,3702,4,978294260,Mad Max (1979),Action|Sci-Fi,2
247,4,2366,4,978294230,King Kong (1933),Action|Adventure|Horror,2
248,4,1387,5,978294199,Jaws (1975),Action|Horror,2
249,4,3527,1,978294008,Predator (1987),Action|Sci-Fi|Thriller,2
250,4,1201,5,978294230,"Good, The Bad and The Ugly, The (1966)",Action|Western,2
251,4,2692,5,978294230,Run Lola Run (Lola rennt) (1998),Action|Crime|Romance,2
252,4,2947,5,978294230,Goldfinger (1964),Action,2
253,4,1240,5,978294260,"Terminator, The (1984)",Action|Sci-Fi|Thriller,2

In [22]:
movieslens_sl333 = pd.concat([movieslens_sl2[movieslens_sl2.columns[0:1]], movieslens_sl22], axis=1)

In [23]:
movieslens_sl333.head(50)

,user_id,Action,Adventure,Animation,Children's,Comedy,Crime,Documentary,Drama,Fantasy,Film-Noir,Horror,Musical,Mystery,Romance,Sci-Fi,Thriller,War,Western
0,1,0.0,0.0,0.0,0.0,0.0,0.0,0.0,10.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
1,1,0.0,0.0,6.0,3.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,3.0,0.0,0.0,0.0,0.0,0.0,0.0
2,1,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,6.0,0.0,3.0,0.0,0.0,0.0,0.0
3,1,0.0,0.0,0.0,0.0,0.0,0.0,0.0,8.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
4,1,0.0,0.0,10.0,5.0,5.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
5,1,6.0,3.0,0.0,0.0,3.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,3.0,0.0,0.0,0.0,0.0
6,1,10.0,5.0,0.0,0.0,0.0,0.0,0.0,5.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
7,1,0.0,0.0,0.0,0.0,10.0,0.0,0.0,5.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
8,1,0.0,0.0,8.0,4.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,4.0,0.0,0.0,0.0,0.0,0.0,0.0
9,1,0.0,8.0,0.0,4.0,0.0,0.0,0.0,4.0,0.0,0.0,0.0,4.0,0.0,0.0,0.0,0.0,0.0,0.0
10,1,0.0,0.0,10.0,5.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,5.0,0.0,0.0,0.0,0.0,0.0,0.0
11,1,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,8.0,0.0,0.0,0.0,0.0,0.0,0.0
12,1,0.0,0.0,0.0,0.0,0.0,0.0,0.0,8.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
13,1,0.0,0.0,0.0,0.0,8.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
14,1,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,10.0,0.0,0.0,0.0,0.0,0.0,0.0
15,1,0.0,0.0,0.0,0.0,8.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
16,1,0.0,0.0,6.0,3.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
17,1,0.0,0.0,8.0,4.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
18,1,0.0,0.0,0.0,0.0,0.0,0.0,0.0,10.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
19,1,0.0,0.0,0.0,0.0,8.0,0.0,0.0,0.0,4.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
20,1,0.0,0.0,0.0,0.0,6.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
21,1,0.0,0.0,6.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
22,1,0.0,0.0,0.0,0.0,10.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,5.0,0.0,0.0,0.0
23,1,0.0,0.0,0.0,0.0,0.0,0.0,0.0,10.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,5.0,0.0
24,1,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,6.0,0.0,0.0,0.0,0.0
25,1,0.0,0.0,10.0,5.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,5.0,0.0,5.0,0.0,0.0,0.0,0.0
26,1,0.0,0.0,0.0,8.0,0.0,0.0,0.0,4.0,4.0,0.0,0.0,0.0,0.0,0.0,4.0,0.0,0.0,0.0
27,1,0.0,0.0,0.0,0.0,0.0,0.0,0.0,8.0,0.0,0.0,0.0,0.0,0.0,4.0,0.0,0.0,0.0,0.0
28,1,0.0,0.0,0.0,0.0,0.0,0.0,0.0,8.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
29,1,0.0,0.0,6.0,0.0,3.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,3.0,0.0,0.0
30,1,0.0,0.0,8.0,4.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
31,1,0.0,0.0,0.0,0.0,0.0,0.0,0.0,8.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
32,1,0.0,8.0,4.0,4.0,4.0,0.0,0.0,0.0,0.0,0.0,0.0,4.0,0.0,0.0,0.0,0.0,0.0,0.0
33,1,0.0,0.0,8.0,4.0,4.0,0.0,0.0,0.0,0.0,0.0,0.0,4.0,0.0,0.0,0.0,0.0,0.0,0.0
34,1,0.0,0.0,8.0,4.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
35,1,0.0,0.0,8.0,4.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,4.0,0.0,0.0,0.0,0.0,0.0,0.0
36,1,0.0,0.0,0.0,0.0,0.0,0.0,0.0,10.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
37,1,0.0,0.0,10.0,5.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,5.0,0.0,0.0,0.0,0.0,0.0,0.0
38,1,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,8.0,0.0,0.0
39,1,0.0,0.0,0.0,0.0,0.0,0.0,0.0,10.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
40,1,0.0,0.0,10.0,5.0,5.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
41,1,0.0,0.0,0.0,0.0,0.0,0.0,0.0,10.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
42,1,0.0,0.0,0.0,0.0,0.0,0.0,0.0,8.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
43,1,8.0,0.0,0.0,0.0,0.0,4.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,4.0,0.0,0.0,0.0,0.0
44,1,8.0,4.0,0.0,0.0,0.0,0.0,0.0,0.0,4.0,0.0,0.0,0.0,0.0,0.0,4.0,0.0,0.0,0.0
45,1,0.0,0.0,0.0,10.0,5.0,0.0,0.0,0.0,0.0,0.0,0.0,5.0,0.0,0.0,0.0,0.0,0.0,0.0
46,1,0.0,0.0,10.0,5.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,5.0,0.0,0.0,0.0,0.0,0.0,0.0
47,1,0.0,0.0,0.0,0.0,0.0,0.0,0.0,8.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
48,1,10.0,0.0,0.0,0.0,0.0,0.0,0.0,5.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,5.0,0.0
49,1,0.0,0.0,0.0,8.0,0.0,0.0,0.0,4.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0

In [24]:
movieslens_sl333[movieslens_sl333['user_id'] ==4]

,user_id,Action,Adventure,Animation,Children's,Comedy,Crime,Documentary,Drama,Fantasy,Film-Noir,Horror,Musical,Mystery,Romance,Sci-Fi,Thriller,War,Western
233,4,0.0,0.0,0.0,0.0,0.0,0.0,0.0,10.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
234,4,6.0,3.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,3.0,3.0,0.0,3.0,0.0
235,4,8.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,4.0
236,4,8.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,4.0,0.0,0.0,0.0,4.0,4.0,0.0,0.0
237,4,8.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,4.0,0.0,0.0
238,4,10.0,5.0,0.0,0.0,0.0,0.0,0.0,0.0,5.0,0.0,0.0,0.0,0.0,0.0,5.0,0.0,0.0,0.0
239,4,10.0,0.0,0.0,0.0,0.0,0.0,0.0,5.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,5.0,0.0
240,4,8.0,4.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,4.0,0.0,0.0,0.0
241,4,-1.0,-0.5,-0.0,-0.0,-0.0,-0.0,-0.0,-0.5,-0.0,-0.0,-0.0,-0.0,-0.0,-0.0,-0.5,-0.0,-0.5,-0.0
242,4,10.0,5.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
243,4,10.0,0.0,0.0,0.0,0.0,0.0,0.0,5.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
244,4,0.0,0.0,0.0,8.0,0.0,0.0,0.0,4.0,4.0,0.0,0.0,0.0,0.0,0.0,4.0,0.0,0.0,0.0
245,4,8.0,0.0,0.0,0.0,0.0,0.0,0.0,4.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
246,4,8.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,4.0,0.0,0.0,0.0
247,4,8.0,4.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,4.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
248,4,10.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,5.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
249,4,-2.0,-0.0,-0.0,-0.0,-0.0,-0.0,-0.0,-0.0,-0.0,-0.0,-0.0,-0.0,-0.0,-0.0,-1.0,-1.0,-0.0,-0.0
250,4,10.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,5.0
251,4,10.0,0.0,0.0,0.0,0.0,5.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,5.0,0.0,0.0,0.0,0.0
252,4,10.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
253,4,10.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,5.0,5.0,0.0,0.0

In [25]:
user_preference = movieslens_sl333.groupby(['user_id']).mean()

In [26]:
user_preference.head()

,Action,Adventure,Animation,Children's,Comedy,Crime,Documentary,Drama,Fantasy,Film-Noir,Horror,Musical,Mystery,Romance,Sci-Fi,Thriller,War,Western
user_id,,,,,,,,,,,,,,,,,,
1,0.792453,0.528302,2.716981,1.849057,1.566038,0.226415,0.00000,2.924528,0.226415,0.000000,0.000000,1.358491,0.000000,0.471698,0.245283,0.283019,0.188679,0.000000
2,2.813953,0.585271,0.000000,0.000000,1.139535,0.445736,0.00000,3.554264,0.023256,0.031008,0.046512,0.000000,0.077519,0.651163,0.453488,0.782946,0.395349,0.100775
3,3.392157,2.382353,0.470588,0.235294,3.019608,0.000000,0.00000,0.764706,0.176471,0.000000,0.068627,0.078431,0.058824,0.323529,0.450980,0.323529,0.156863,0.647059
4,7.095238,0.976190,0.000000,0.380952,0.000000,0.238095,0.00000,1.309524,0.428571,0.000000,0.619048,0.000000,0.000000,0.380952,1.309524,0.571429,0.357143,0.428571
5,0.474747,0.171717,0.141414,0.171717,1.553030,0.489899,0.19697,2.073232,0.000000,0.085859,0.217172,0.037879,0.103535,0.429293,0.196970,0.404040,0.083333,0.040404

In [41]:
toy_story_features = movies_list.loc[0][geners] 
toy_story_features

Action         0
Adventure      0
Animation      2
Children's     1
Comedy         1
Crime          0
Documentary    0
Drama          0
Fantasy        0
Film-Noir      0
Horror         0
Musical        0
Mystery        0
Romance        0
Sci-Fi         0
Thriller       0
War            0
Western        0
Name: 0, dtype: object

In [31]:
user_4_preference = user_preference.loc[[4]].T.squeeze()

In [37]:
user_4_preference

Action         7.095238
Adventure      0.976190
Animation      0.000000
Children's     0.380952
Comedy         0.000000
Crime          0.238095
Documentary    0.000000
Drama          1.309524
Fantasy        0.428571
Film-Noir      0.000000
Horror         0.619048
Musical        0.000000
Mystery        0.000000
Romance        0.380952
Sci-Fi         1.309524
Thriller       0.571429
War            0.357143
Western        0.428571
Name: 4, dtype: float64

In [34]:
#in production you would use np.dot instead of writing your own dot product function.
def dot_product(vector_1, vector_2):  
    return sum([ i*j for i,j in zip(vector_1, vector_2)])

def get_movie_score(movie_features, user_preferences):  
    return dot_product(movie_features, user_preferences)

In [48]:
toy_story_user_predicted_score = dot_product(toy_story_features, user_4_preference)  
toy_story_user_predicted_score

0.38095238095238093

In [47]:
user_4_preference

Action         7.095238
Adventure      0.976190
Animation      0.000000
Children's     0.380952
Comedy         0.000000
Crime          0.238095
Documentary    0.000000
Drama          1.309524
Fantasy        0.428571
Film-Noir      0.000000
Horror         0.619048
Musical        0.000000
Mystery        0.000000
Romance        0.380952
Sci-Fi         1.309524
Thriller       0.571429
War            0.357143
Western        0.428571
Name: 4, dtype: float64

In [59]:
def get_movie_recommendations(user_preferences, n_recommendations):  
    #we add a column to the movies_df dataset with the calculated score for each movie for the given user
    movies_list['score'] = movies_list[geners].apply(get_movie_score, 
                                                           args=([user_preferences]), axis=1)
    return movies_list.sort_values(by=['score'], ascending=False)[['title','genres','score']][:n_recommendations]

In [62]:
get_movie_recommendations(user_4_preference, 100).head()

,title,genres,score
1178,Star Wars: Episode V - The Empire Strikes Back...,Action|Adventure|Drama|Sci-Fi|War,18.142857
2253,Soldier (1998),Action|Adventure|Sci-Fi|Thriller|War,17.404762
1807,Deep Impact (1998),Action|Drama|Sci-Fi|Thriller,17.380952
1192,Star Wars: Episode VI - Return of the Jedi (1983),Action|Adventure|Romance|Sci-Fi|War,17.214286
606,Heavy Metal (1981),Action|Adventure|Animation|Horror|Sci-Fi,17.095238

In [63]:
user_3_preference = user_preference.loc[[3]].T.squeeze()

In [64]:
get_movie_recommendations(user_3_preference, 100)

,title,genres,score
1197,Army of Darkness (1993),Action|Adventure|Comedy|Horror|Sci-Fi,12.705882
1539,Men in Black (1997),Action|Adventure|Comedy|Sci-Fi,12.637255
2336,"Jewel of the Nile, The (1985)",Action|Adventure|Comedy|Romance,12.509804
2337,Romancing the Stone (1984),Action|Adventure|Comedy|Romance,12.509804
1179,"Princess Bride, The (1987)",Action|Adventure|Comedy|Romance,12.509804
376,True Lies (1994),Action|Adventure|Comedy|Romance,12.509804
2651,Inspector Gadget (1999),Action|Adventure|Children's|Comedy,12.421569
1972,Condorman (1981),Action|Adventure|Children's|Comedy,12.421569
680,Operation Dumbo Drop (1995),Action|Adventure|Comedy|War,12.343137
1241,Evil Dead II (Dead By Dawn) (1987),Action|Adventure|Comedy|Horror,12.254902
2666,"Golden Child, The (1986)",Action|Adventure|Comedy,12.186275
2654,Mystery Men (1999),Action|Adventure|Comedy,12.186275
3035,Midnight Run (1988),Action|Adventure|Comedy|Crime,12.186275
2810,Operation Condor (Feiying gaiwak) (1990),Action|Adventure|Comedy,12.186275
151,Batman Forever (1995),Action|Adventure|Comedy|Crime,12.186275
2811,Operation Condor 2 (Longxiong hudi) (1990),Action|Adventure|Comedy,12.186275
1356,Batman Returns (1992),Action|Adventure|Comedy|Crime,12.186275
548,"Three Musketeers, The (1993)",Action|Adventure|Comedy,12.186275
2630,Arachnophobia (1990),Action|Comedy|Sci-Fi|Thriller,10.578431
3197,Man Bites Dog (C'est arriv� pr�s de chez vous)...,Action|Comedy|Crime|Drama,10.568627
3115,Montana (1998),Action|Comedy|Crime|Drama,10.568627
1932,Lethal Weapon 2 (1989),Action|Comedy|Crime|Drama,10.568627
20,Get Shorty (1995),Action|Comedy|Drama,10.568627
1931,Lethal Weapon (1987),Action|Comedy|Crime|Drama,10.568627
386,Faster Pussycat! Kill! Kill! (1965),Action|Comedy|Drama,10.568627
1445,Best Men (1997),Action|Comedy|Crime|Drama,10.568627
1849,Lethal Weapon 4 (1998),Action|Comedy|Crime|Drama,10.568627
1933,Lethal Weapon 3 (1992),Action|Comedy|Crime|Drama,10.568627
1847,Buffalo 66 (1998),Action|Comedy|Drama,10.568627
1178,Star Wars: Episode V - The Empire Strikes Back...,Action|Adventure|Drama|Sci-Fi|War,10.539216
...,...,...,...
481,Last Action Hero (1993),Action|Comedy,9.803922
2513,Twin Dragons (Shuang long hui) (1992),Action|Comedy,9.803922
434,"Cowboy Way, The (1994)",Action|Comedy,9.803922
3139,Loaded Weapon 1 (1993),Action|Comedy,9.803922
416,Beverly Hills Cop III (1994),Action|Comedy,9.803922
1841,I Went Down (1997),Action|Comedy|Crime,9.803922
3641,Action Jackson (1988),Action|Comedy,9.803922
383,"Low Down Dirty Shame, A (1994)",Action|Comedy,9.803922
3671,Big Trouble in Little China (1986),Action|Comedy,9.803922
356,I Love Trouble (1994),Action|Comedy,9.803922
3206,"Boondock Saints, The (1999)",Action|Comedy,9.803922
3199,Stop! Or My Mom Will Shoot (1992),Action|Comedy,9.803922
2101,Wrongfully Accused (1998),Action|Comedy,9.803922
1789,Mr. Nice Guy (1997),Action|Comedy,9.803922
1563,Money Talks (1997),Action|Comedy,9.803922
1407,Beverly Hills Ninja (1997),Action|Comedy,9.803922
3828,Bait (2000),Action|Comedy,9.803922
2418,"Blood, Guts, Bullets and Octane (1998)",Action|Comedy,9.803922
2388,Running Scared (1986),Action|Comedy,9.803922
2036,Tron (1982),Action|Adventure|Fantasy|Sci-Fi,9.794118
257,Star Wars: Episode IV - A New Hope (1977),Action|Adventure|Fantasy|Sci-Fi,9.794118
2559,Star Wars: Episode I - The Phantom Menace (1999),Action|Adventure|Fantasy|Sci-Fi,9.794118
1630,Starship Troopers (1997),Action|Adventure|Sci-Fi|War,9.774510
158,Congo (1995),Action|Adventure|Mystery|Sci-Fi,9.676471
957,"African Queen, The (1951)",Action|Adventure|Romance|War,9.647059
2931,"Princess Mononoke, The (Mononoke Hime) (1997)",Action|Adventure|Animation,9.637255
2572,Superman II (1980),Action|Adventure|Sci-Fi,9.617647
2571,Superman (1978),Action|Adventure|Sci-Fi,9.617647
2574,Superman IV: The Quest for Peace (1987),Action|Adventure|Sci-Fi,9.617647
313,Stargate (1994),Action|Adventure|Sci-Fi,9.617647